// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc8yW_rm_XPdVx1pzBeo5hJR2LBv3rZ0M',
    appId: '1:1052481672494:web:77065b06950dd6823bd6bf',
    messagingSenderId: '1052481672494',
    projectId: 'hooder-6a742',
    authDomain: 'hooder-6a742.firebaseapp.com',
    databaseURL: 'https://hooder-6a742-default-rtdb.firebaseio.com',
    storageBucket: 'hooder-6a742.appspot.com',
    measurementId: 'G-7HPGQ5KXDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_pAmXzhKSD_6hr9vVM9597qREn1LY01M',
    appId: '1:1052481672494:android:5e342d488defdcff3bd6bf',
    messagingSenderId: '1052481672494',
    projectId: 'hooder-6a742',
    databaseURL: 'https://hooder-6a742-default-rtdb.firebaseio.com',
    storageBucket: 'hooder-6a742.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIICpGG7ibVasQOpLCrSMSGJtnktvyxwE',
    appId: '1:1052481672494:ios:85f73998c229d18a3bd6bf',
    messagingSenderId: '1052481672494',
    projectId: 'hooder-6a742',
    databaseURL: 'https://hooder-6a742-default-rtdb.firebaseio.com',
    storageBucket: 'hooder-6a742.appspot.com',
    iosClientId: '1052481672494-eglokimg8c6c4l3nrfpg3ra9en40hv3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
